global.mastery_data = [];																			
global.mastery_data[	0	] = {	name : 	""	, hero :	"None"	, column :	0	, tier :	0	, max_points :	0	, key :	""	, value :	0	, desc :	""	}
global.mastery_data[	1	] = {	name : 	"Strength"	, hero :	"Abel"	, column :	1	, tier :	1	, max_points :	5	, key :	"damageBns"	, value :	0.3	, desc :	"Increase Damage by 0.3"	}
global.mastery_data[	2	] = {	name : 	"Arc Speed"	, hero :	"Abel"	, column :	1	, tier :	2	, max_points :	3	, key :	""	, value :	10	, desc :	"Increase the travel distance of Arc Slash by 10%"	}
global.mastery_data[	3	] = {	name : 	"EX Arc Slash"	, hero :	"Abel"	, column :	1	, tier :	3	, max_points :	1	, key :	""	, value :	1	, desc :	"Reduce the cost of EX Arc Slash by 50%"	}
global.mastery_data[	4	] = {	name : 	"Vitality"	, hero :	"Abel"	, column :	2	, tier :	1	, max_points :	5	, key :	"hpPlv"	, value :	0.4	, desc :	"Increase Hp Per Level by 0.4"	}
global.mastery_data[	5	] = {	name : 	"Toughness"	, hero :	"Abel"	, column :	2	, tier :	2	, max_points :	3	, key :	""	, value :	2	, desc :	"Reduce Damage taken by 2"	}
global.mastery_data[	6	] = {	name : 	"Berserk"	, hero :	"Abel"	, column :	2	, tier :	3	, max_points :	1	, key :	"damageIncrease"	, value :	20	, desc :	"After taking damage, gain 20% Increased Damage for 10 seconds"	}
global.mastery_data[	7	] = {	name : 	"Heavy Swing"	, hero :	"Abel"	, column :	3	, tier :	1	, max_points :	5	, key :	"critDamage"	, value :	2	, desc :	"Increase Critical Hit Damage by 2%"	}
global.mastery_data[	8	] = {	name : 	"Bladestorm"	, hero :	"Abel"	, column :	3	, tier :	2	, max_points :	3	, key :	""	, value :	5	, desc :	"Increase Crit by 5 while using Whirlwind"	}
global.mastery_data[	9	] = {	name : 	"Eye of the Storm"	, hero :	"Abel"	, column :	3	, tier :	3	, max_points :	1	, key :	""	, value :	1	, desc :	"Whirlwind destroys projectiles for 1 second after being used (reduced to .5s while using ULT)"	}
global.mastery_data[	10	] = {	name : 	""	, hero :	"None"	, column :	0	, tier :	0	, max_points :	0	, key :	""	, value :	0	, desc :	""	}
global.mastery_data[	11	] = {	name : 	"Vitality"	, hero :	"Arthur"	, column :	1	, tier :	1	, max_points :	5	, key :	"defenseBns"	, value :	1	, desc :	"Increase Defense by 1"	}
global.mastery_data[	12	] = {	name : 	"Spiked Shield"	, hero :	"Arthur"	, column :	1	, tier :	2	, max_points :	3	, key :	""	, value :	5	, desc :	"While using Defend, return 10% Damage to enemies that hit your shield"	}
global.mastery_data[	13	] = {	name : 	"EX Defend"	, hero :	"Arthur"	, column :	1	, tier :	3	, max_points :	1	, key :	""	, value :	1	, desc :	"Reduce the cost of EX Defend by 50%"	}
global.mastery_data[	14	] = {	name : 	"Might"	, hero :	"Arthur"	, column :	2	, tier :	1	, max_points :	5	, key :	"damagePct"	, value :	0.01	, desc :	"Increase Damage by 1%"	}
global.mastery_data[	15	] = {	name : 	"Wrist Flick"	, hero :	"Arthur"	, column :	2	, tier :	2	, max_points :	3	, key :	""	, value :	3	, desc :	"Hammer Throw deals 8% increased Damage"	}
global.mastery_data[	16	] = {	name : 	""	, hero :	"Arthur"	, column :	2	, tier :	3	, max_points :	1	, key :	""	, value :	1	, desc :	"Reduce the CD of Hammer Throw by 3. Hammer Throw pulls enemies 5m towards you."	}
global.mastery_data[	17	] = {	name : 	"Fortitude"	, hero :	"Arthur"	, column :	3	, tier :	1	, max_points :	5	, key :	"damageReductionBns"	, value :	0.02	, desc :	"Increase Damage Reduction by 2%"	}
global.mastery_data[	18	] = {	name : 	"Power Attack"	, hero :	"Arthur"	, column :	3	, tier :	2	, max_points :	3	, key :	""	, value :	10	, desc :	"Increase Hitstun duration by 10%"	}
global.mastery_data[	19	] = {	name : 	""	, hero :	"Arthur"	, column :	3	, tier :	3	, max_points :	1	, key :	""	, value :	1	, desc :	"The first time your Armor breaks during combat, increase Damage by 20% for 10s."	}
global.mastery_data[	20	] = {	name : 	""	, hero :	"None"	, column :	0	, tier :	0	, max_points :	0	, key :	""	, value :	0	, desc :	""	}
global.mastery_data[	21	] = {	name : 	"Focus"	, hero :	"Enzo"	, column :	1	, tier :	1	, max_points :	5	, key :	"critBns"	, value :	1.5	, desc :	"Increase the Range of your Basic Attacks by 1."	}
global.mastery_data[	22	] = {	name : 	""	, hero :	"Enzo"	, column :	1	, tier :	2	, max_points :	3	, key :	""	, value :	0	, desc :	"Basic Attacks deal 1 additional Damage."	}
global.mastery_data[	23	] = {	name : 	"Sniper"	, hero :	"Enzo"	, column :	1	, tier :	3	, max_points :	1	, key :	""	, value :	0	, desc :	"Basic Attacks deal increased Damage based on the distance traveled. (up to 20% bonus Damage)"	}
global.mastery_data[	24	] = {	name : 	"Dexterity"	, hero :	"Enzo"	, column :	2	, tier :	1	, max_points :	5	, key :	"attackSpeedPct"	, value :	0.01	, desc :	"Increase Attack Speed by 1%"	}
global.mastery_data[	25	] = {	name : 	"Crit"	, hero :	"Enzo"	, column :	2	, tier :	2	, max_points :	3	, key :	""	, value :	5	, desc :	"Perfect Shot increases Crit by 5"	}
global.mastery_data[	26	] = {	name : 	""	, hero :	"Enzo"	, column :	2	, tier :	3	, max_points :	1	, key :	""	, value :	0	, desc :	"Increase Charge Speed by 20%."	}
global.mastery_data[	27	] = {	name : 	"Dexterity"	, hero :	"Enzo"	, column :	3	, tier :	1	, max_points :	5	, key :	"moveSpeedBns"	, value :	2	, desc :	"Increase Move Speed by 2"	}
global.mastery_data[	28	] = {	name : 	""	, hero :	"Enzo"	, column :	3	, tier :	2	, max_points :	3	, key :	""	, value :	15	, desc :	"Increase the effectiveness of Slows by 15%"	}
global.mastery_data[	29	] = {	name : 	"Combat Manuevers"	, hero :	"Enzo"	, column :	3	, tier :	3	, max_points :	1	, key :	""	, value :	0	, desc :	"Throw 2 additional Caltraps and increase Leap distance by 30%"	}
global.mastery_data[	30	] = {	name : 	""	, hero :	"None"	, column :	0	, tier :	0	, max_points :	0	, key :	""	, value :	0	, desc :	""	}
global.mastery_data[	31	] = {	name : 	"Insight"	, hero :	"Kai"	, column :	1	, tier :	1	, max_points :	5	, key :	"cooldownBns"	, value :	2	, desc :	"Increase Cooldown by 2"	}
global.mastery_data[	32	] = {	name : 	"Spirit"	, hero :	"Kai"	, column :	1	, tier :	2	, max_points :	3	, key :	"energyGain"	, value :	8	, desc :	"Increase Energy gain by 8%"	}
global.mastery_data[	33	] = {	name : 	"Third Eye"	, hero :	"Kai"	, column :	1	, tier :	3	, max_points :	1	, key :	""	, value :	1	, desc :	"Increase Ult duration by 50%"	}
global.mastery_data[	34	] = {	name : 	"Agility"	, hero :	"Kai"	, column :	2	, tier :	1	, max_points :	5	, key :	"moveSpeedPct"	, value :	0.02	, desc :	"Increase Move Speed by 1%"	}
global.mastery_data[	35	] = {	name : 	"Tempest"	, hero :	"Kai"	, column :	2	, tier :	2	, max_points :	3	, key :	""	, value :	10	, desc :	""	}
global.mastery_data[	36	] = {	name : 	""	, hero :	"Kai"	, column :	2	, tier :	3	, max_points :	1	, key :	""	, value :	1	, desc :	"Reduce cost of EX Windsweep by 50%"	}
global.mastery_data[	37	] = {	name : 	"Speedy man"	, hero :	"Kai"	, column :	3	, tier :	1	, max_points :	5	, key :	"evade"	, value :	3	, desc :	"Increase Attack Speed by 1.5"	}
global.mastery_data[	38	] = {	name : 	"Windstorm"	, hero :	"Kai"	, column :	3	, tier :	2	, max_points :	3	, key :	"damagePct"	, value :	0.03	, desc :	"Basic attacks do something while Zephyr is active"	}
global.mastery_data[	39	] = {	name : 	"Typhoon"	, hero :	"Kai"	, column :	3	, tier :	3	, max_points :	1	, key :	""	, value :	1	, desc :	""	}