global.spawn_data = {};									
global.spawn_data[$	"Viper"	] = {	region : 	[1,2]	, level_req :	1	, spawn_type :	SPAWN_TYPE.BASIC	}
global.spawn_data[$	"Giblin"	] = {	region : 	[1,2]	, level_req :	1	, spawn_type :	SPAWN_TYPE.BASIC	}
global.spawn_data[$	"Giblin Bomber"	] = {	region : 	[1,2]	, level_req :	3	, spawn_type :	SPAWN_TYPE.BASIC	}
global.spawn_data[$	"Giblin Shaman"	] = {	region : 	[1,2]	, level_req :	5	, spawn_type :	SPAWN_TYPE.BASIC	}
global.spawn_data[$	"Mossman"	] = {	region : 	[1,2]	, level_req :	7	, spawn_type :	SPAWN_TYPE.BASIC	}
global.spawn_data[$	"Viper Nest"	] = {	region : 	[2]	, level_req :	10	, spawn_type :	SPAWN_TYPE.BASIC	}
global.spawn_data[$	"Mosslad"	] = {	region : 	[2]	, level_req :	12	, spawn_type :	SPAWN_TYPE.BASIC	}
global.spawn_data[$	"Viper Elite"	] = {	region : 	[1,2]	, level_req :	10	, spawn_type :	SPAWN_TYPE.ELITE	}
global.spawn_data[$	"Giblin Elite"	] = {	region : 	[1,2]	, level_req :	12	, spawn_type :	SPAWN_TYPE.ELITE	}
global.spawn_data[$	"Giblin Bomber Elite"	] = {	region : 	[1,2]	, level_req :	15	, spawn_type :	SPAWN_TYPE.ELITE	}
global.spawn_data[$	"Giblin Shaman Elite"	] = {	region : 	[1,2]	, level_req :	17	, spawn_type :	SPAWN_TYPE.ELITE	}
global.spawn_data[$	"Spider"	] = {	region : 	[3,4]	, level_req :	1	, spawn_type :	SPAWN_TYPE.BASIC	}
global.spawn_data[$	"Corse Soldier"	] = {	region : 	[3,4]	, level_req :	1	, spawn_type :	SPAWN_TYPE.BASIC	}
global.spawn_data[$	"Corse Marksman"	] = {	region : 	[3,4]	, level_req :	1	, spawn_type :	SPAWN_TYPE.BASIC	}
global.spawn_data[$	"Corse Warlock"	] = {	region : 	[3,4]	, level_req :	3	, spawn_type :	SPAWN_TYPE.BASIC	}
global.spawn_data[$	"Cyclops"	] = {	region : 	[3,4]	, level_req :	5	, spawn_type :	SPAWN_TYPE.BASIC	}
global.spawn_data[$	"Cave Bat"	] = {	region : 	[3,4]	, level_req :	10	, spawn_type :	SPAWN_TYPE.BASIC	}
global.spawn_data[$	"Spooder Egg"	] = {	region : 	[4]	, level_req :	6	, spawn_type :	SPAWN_TYPE.BASIC	}
global.spawn_data[$	"Crawler"	] = {	region : 	[4]	, level_req :	12	, spawn_type :	SPAWN_TYPE.BASIC	}